### ISSUE TITLE
Gateway Issue

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-server#128]
Hi @ralphhanna 

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/0e162b1a-330b-4512-adaf-f639f6497820)

Please note the issue in the above example. The workflow abruptly stops at the gateway. 

The bpmn is already in your demo site named `TestUseCaseMS`.

Please look into this as soon as possible.

Thanks.

**Comment by ralphhanna** [comment]
Fixed in Release 1.4.6, now available.

Thanks very much
