### ISSUE TITLE
NestJs Integration

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#130]
So far I'd tested integrate with nestjs and using openapi. it work smoothly, below is example of controller, service class, and swagger-ui result, it work as expected!

```typescript
//controller
import { Controller, Get,Post,Req,Param} from '@nestjs/common';
import { AppService } from './app.service';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  //get all workflow
  @Get('/')
  getWorkflows() {
    return this.appService.getPendingWorkflows();
  }
  //create workflow
  @Post('/:workflow')
  postStart(@Param('workflow') workflow:string) {
    return this.appService.startWorkflow(workflow);
  }
  // others required endpoint
  //get /:workflow/:id  //fetch info
  //put /:workflow/:id  //update info
  //post/:workflow/:id/:taskId  //invoke {user:xxx}
  //...
}

```

```typescript
// service class
import { Injectable,Logger } from '@nestjs/common';
import {BPMNServer} from 'bpmn-server'
import {configuration} from './configuration'

@Injectable()
export class AppService {
  private readonly logger = new Logger();

  bpmnServer:BPMNServer
  constructor(){
    this.bpmnServer = new BPMNServer(configuration)
  }

  async startWorkflow(workflow:string){
    const result =  await this.bpmnServer.engine.start(workflow);        
    return {
      id: result.id,
      data:result.getData('id'),
      status: result.status
    }
  }
  async getPendingWorkflows(){
    const tmp:any[] = await this.bpmnServer.dataStore.findInstances({
      status:'running',
    },'summary')

    const result = tmp.map((proc)=>({
      id: proc.id,
      workflowname: proc.name,
      startedAt: proc.startedAt,
      tasks :proc.items
              .filter((task)=>task.status=='wait')
              .map((task)=>({
                id:task.id,
                type:task.type,
                assignee:task.assignee,
                candidateUsers:task.candidateUsers,
                candidateGroups:task.candidateGroups
              }))
    }))

    return result
  }
}

```

![sample](https://github.com/bpmnServer/bpmn-server/assets/1889979/0b1df054-c6cf-4b9e-b756-133413c0dc89)

I'm curious so far any documentation of upload bpmn file? I don't know the process of upload file until the engine support the new definition.

**Comment by kstan79** [comment]
thanks reply, i mean so far any reference of upload bpmn file? Is it I put the file in defination folder it will auto generate new model, or i need to read file content then run `await api.model.saveModel('deleteLater', src, null);`?

I saw there is svg property too, I shall update manually in model collection?

thanks `getPendingWorkflows` advise!

**Comment by ralphhanna** [comment]
auto generate uses the `saveModel` function
But you can use `saveModel` for files outside of definitions folder or when you keep all your models in DB.
The last parameter is the svg

```js
     async saveModel(name, source,svg) 

```

**Comment by ralphhanna** [comment]
Can you please share a sample project for nestJs, OpenAPI and swagger 
I will integrate into next release
Thanks very much

**Comment by kstan79** [comment]
Will do, also will write setup documentation for you

**Comment by kstan79** [comment]
you may refer minimal example here:
https://github.com/kstan79/nestjs-bpmn-server

**Comment by kstan79** [comment]
since you will integrate with nestjs at next release, i think it is better i wait your latest release, Im worry it will have huge impact. By the way, I'd more complex working example with:
1. keycloak integration
2. swagger-ui perform api-key/oauth2 autorization 
3. some working middleware, decorators, practise of request scope user.context
4. api-request logging
5. mongodb transaction (if neccessary)
