### ISSUE TITLE
What is "option" in start()

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#131]
I saw there is 1 `options` property as below however there is no proper explanation. Can briefly describe how to use it? I give below as example:
```typescript
const result =  await this.bpmnServer.engine.start( 'workflow1', {id:'123',date:'2000-01-01','leavetype':'AL'}, null,
 'kstan; ,options);
```

Assume I have a leave application wish to get supervisor approve, as we know different employee have different supervisor so we wish to implement dynamic group in process definations.

instead of I define supervisor in `data` which will pollute the data, im thinking is it possible i make use the `options` as below:
`{supervisor:user1}`. I'd tried before and it seems it doesn't store any info in mongodb.

**Comment by ralphhanna** [comment]
Currently, options is only available through process execution and has limited use.
You can accomplish the above by:
1. Have an event trigger define the supervisor and store it in `item.vars` instead of `data`
2. Use new feature of `candidateUsers` by setting `item.candidateUsers=[supervisor.userid]`

**Comment by kstan79** [comment]
> Currently, options is only available through process execution and has limited use.
> 
> You can accomplish the above by:
> 
> 1. Have an event trigger define the supervisor and store it in `item.vars` instead of `data`
> 
> 2. Use new feature of `candidateUsers` by setting `item.candidateUsers=[supervisor.userid]` 

It seems like we need to run another execution after process start. So far any way to achieve similar result during imitate (start())?

**Comment by ralphhanna** [comment]
Here is an example of what you are trying to do:
### Output:

![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/34837a45-3654-4f54-9dee-578fafa2370b)


To implement the above your need the following:

### 1 Set Initiator at start task
The user that starts the task is now saved in `data.requester`
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/2a92ace6-2f03-4b31-8e82-ee9e080de8d4)
### 2 Set Assignee for Request
Only the one started the task can/should make the Request
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/2984e56f-da7c-4481-9f19-09bd7e49f074)
### 3 Set Assignee for Approve
Calculate who is the supervisor, you have to add this code 
and make that user the Assignee for the Approve task

![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/0b0a40e0-fcf8-44c6-8fd2-fb8f3a0bfafb)
