### ISSUE TITLE
Too much console log

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#133]
I'm trying to put this project into main product, however too much console log. 

![toomuchconsole](https://github.com/bpmnServer/bpmn-server/assets/1889979/f7dc766d-6b1a-47d8-ac38-edad222701f1)

I'm suggest to implement log level control like using LOGGER setting in `.env`, example:
```sh
LOGGER="error,warn,fatal,log"  #verbose, debug hidden
```

**Comment by ralphhanna** [comment]
For now, Please change the initialization code in the app.ts to the following. Next release will be an option in .env

```js
		const wflogger = new Logger({ toConsole: true });
		this.bpmnServer = new BPMNServer(config,wflogger);

```
Thanks
