### ISSUE TITLE
types in findInstance(s)

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#137]
I would like to suggest implement type in findInstance(s). It is not high priority but definitely can control code quality

**Comment by ralphhanna** [comment]
New Code in release 2.0.0
```js
    findItem(query: any): Promise<IItemData>;
    findInstance(query: any, options: any): Promise<IInstanceData>;
    findInstances(query: any, option: 'summary' | 'full'): Promise<IInstanceData[]>;
    findItems(query: any): Promise<IItemData[]>;

```

**Comment by kstan79** [comment]
reopen cause not yet release

**Comment by ralphhanna** [comment]
Please Test this added feature in new release.

https://github.com/bpmnServer/bpmn-web
