### ISSUE TITLE
deleted executionEvent(context, event) no assignee/candidateUsers/groups and etc property

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#138]
First of all, sorry of submit many issue here, I'm carefully evaluate every single area as I can to ensure this wonderful project can reach GA stage (so i can use in productio). All issue i found will raise up here, after all important issue been track I will help coding and send PR.

base on documentation seems best place to implement push notification when usertask activated is use appDelegates/executionEvent. However there is no sufficient property in `context.item`, is there any others suitable place to do that?

Im tried to use userTask listener (delegates) seems no luck:
1. `taskListener` : no execution
2. `executionListener`: cause application error
3.  is taskListener only support `script`? I saw example `Buy Used Car.bpmn` is using that.
4. IMHO script provide short and sharp way for try the flow but not able to ensure the source code quality (no type, no syntax highlight)
 
```ts
//userTaskMessage
export const userTaskMessage = (a,b,c) =>{
    console.log("AAA",'BBB','CCC')
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_1" name="approve1" isExecutable="false">
    <bpmn:extensionElements />
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1a63g0z</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_0qpgd23">
      <bpmn:incoming>Flow_1x9zeai</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1x9zeai" sourceRef="Activity_07kqvhs" targetRef="Event_0qpgd23" />
    <bpmn:sequenceFlow id="Flow_1a63g0z" sourceRef="StartEvent_1" targetRef="Activity_0je8vny" />
    <bpmn:userTask id="Activity_07kqvhs" name="approve1">
      <bpmn:extensionElements>
        <camunda:taskListener delegateExpression="userTaskMessage" event="create" />  
        <camunda:executionListener delegateExpression="userTaskMessage" event="start" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1ch6wn0</bpmn:incoming>
      <bpmn:outgoing>Flow_1x9zeai</bpmn:outgoing>
    </bpmn:userTask>
    <bpmn:sequenceFlow id="Flow_1ch6wn0" sourceRef="Activity_0je8vny" targetRef="Activity_07kqvhs" />
    <bpmn:serviceTask id="Activity_0je8vny" name="say hello" camunda:delegateExpression="hello">
      <bpmn:incoming>Flow_1a63g0z</bpmn:incoming>
      <bpmn:outgoing>Flow_1ch6wn0</bpmn:outgoing>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="-98" y="72" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0qpgd23_di" bpmnElement="Event_0qpgd23">
        <dc:Bounds x="302" y="72" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1odv9ki_di" bpmnElement="Activity_07kqvhs">
        <dc:Bounds x="130" y="50" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1ble3e5_di" bpmnElement="Activity_0je8vny">
        <dc:Bounds x="-20" y="50" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_1x9zeai_di" bpmnElement="Flow_1x9zeai">
        <di:waypoint x="230" y="90" />
        <di:waypoint x="302" y="90" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1a63g0z_di" bpmnElement="Flow_1a63g0z">
        <di:waypoint x="-62" y="90" />
        <di:waypoint x="-20" y="90" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1ch6wn0_di" bpmnElement="Flow_1ch6wn0">
        <di:waypoint x="80" y="90" />
        <di:waypoint x="130" y="90" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
xml

**Comment by kstan79** [comment]
> 1. As you mentioned Execution Listener, only JavaScript is supported, but this JavaScript can call your appDelegates and appServices

How can I execute delegate code from script? can give short source code sniplet?

>2. Service Task, that can call your appServices directly as discussed earlier and this is more suitable for your use case they can call async methods in the current production release.

yes I know can do from service task, but I require to access the property of submitted data and `assignee/candidateUsers/groups` from userTask (previous node) which is not directly accessible (and don't know how to access it), since everything is dynamic.

> Currently, I am thinking of have a Custom Task Class that you can assign any Task(User or Service) a JavaScript/TypeScript Class that handle these events, any thoughts?

I not sure what you mean `Custom Task Class`, you mean it is something similar with #134 `invoiceDelegates`?
 
a. true: it is developer friendly cause it is clear and consider well documented in bpmn. 
b. if you mean others then you may give example to elaborate.

> createNotification(item,to,when,message,template)

this is very interesting topic, but you didn't state where/when this code executed. Beside, I don't know what is `eventListener`, you mean `executionListener` as below picture?

![listener](https://github.com/bpmnServer/bpmn-server/assets/1889979/cf5e4e2d-401d-4037-86e1-26ca76e52d73)

Overall, sad to say I'm recommend redesign this scope, use modern and clean pattern:

```ts
const sampleworkflowlisten1 = bpmn.subscribeTaskEvent('sampleworkflow' )
       .init((a,b,c) => {}),
       .end((a,b,c) => {})

const  tasklistener1 = bpmn.subscribeTaskEvent('sampleworkflow1' , 'usertask1', )
       .before((a,b,c) => {}),
       .after((a,b,c) => {})

```
the benefit of above design allow us to arrange sort code in tidy view, and easy to review and bug fix

**Comment by ralphhanna** [comment]
Sorry, I didn't notice your questions before:
1. Yes I ment executionListener as you have shown before, correct only JS inside the mode 
2  Currently you can define listeners like this:
```js
        const listener = server.listener;

    listener.on('end', function ({ context, event }) {
        console.log('----->'+event+" "+ context.item.elementId);
    });

    listener.on('all', function ({ context, event, }) {
//        console.log('-----> Event:', event);
    });

    listener.on('wait', function ({ context, event }) {
        console.log('-----> wait 1' + event , context.instance.id,context.item.id);
    });}
```

This is done for all objects and all events 

What do you mean by `before` , `after` in :
```
const  tasklistener1 = bpmn.subscribeTaskEvent('sampleworkflow1' , 'usertask1', )
       .before((a,b,c) => {})
       .after((a,b,c) => {})
       .anyothers((a,b,c)=>{})
       .build() //optional, may not neccessary to build it
```

3. Notify is already done, you don't have to use it , it has a bit of trick that requires bpmn-server, which is delayed notification and cancel of notification if task is done..

Thanks

**Comment by ralphhanna** [comment]
One more item, Are you suggesting to have executionListener support a class as well?
Currently, you can do this inside the JS
```
appDelegate.method1(...);
appServices.method2(...);
appUtils.method3(...);   // Release 2.0.0.

```
and pass any parameters include item, which has access the Node object the entire model

If you specify another class then we have initialize it, more complex just java stuff, trying to keep simple and light.

**Comment by kstan79** [comment]
> Sorry, I didn't notice your questions before:
> 
> 1. Yes I ment executionListener as you have shown before, correct only JS inside the mode
>    2  Currently you can define listeners like this:
> 
> ```js
>         const listener = server.listener;
> 
>     listener.on('end', function ({ context, event }) {
>         console.log('----->'+event+" "+ context.item.elementId);
>     });
> 
>     listener.on('all', function ({ context, event, }) {
> //        console.log('-----> Event:', event);
>     });
> 
>     listener.on('wait', function ({ context, event }) {
>         console.log('-----> wait 1' + event , context.instance.id,context.item.id);
>     });}
> ```

noted it maybe useful. 

> 
> This is done for all objects and all events
> 
> What do you mean by `before` , `after` in :

sorry, is start/end, as far as i know all component have before/after, included service task, user task. it this very useful. 
![beforeafter](https://github.com/bpmnServer/bpmn-server/assets/1889979/d413af80-9c25-4e7c-8287-d9e9afa9d1e8)

> 
> ```
> const  tasklistener1 = bpmn.subscribeTaskEvent('sampleworkflow1' , 'usertask1', )
>        .before((a,b,c) => {})
>        .after((a,b,c) => {})
>        .anyothers((a,b,c)=>{})
>        .build() //optional, may not neccessary to build it
> ```
> 
> 3. Notify is already done, you don't have to use it , it has a bit of trick that requires bpmn-server, which is delayed notification and cancel of notification if task is done..

oh. may have a try
> 
> Thanks

**Comment by kstan79** [comment]
> One more item, Are you suggesting to have executionListener support a class as well? Currently, you can do this inside the JS
> 
> ```
> appDelegate.method1(...);
> appServices.method2(...);
> appUtils.method3(...);   // Release 2.0.0.
> ```
There is few places in bpmn allow define execution of delegate:
1. service task implementation
2. start/end execution listener
3. send/receive task
4. business rules task

So far supported?

> 
> and pass any parameters include item, which has access the Node object the entire model
> 
> If you specify another class then we have initialize it, more complex just java stuff, trying to keep simple and light.

**Comment by ralphhanna** [comment]
### Delegate Expression
`Service Task` ,`Send Task` and `Business Rule Task` use **Delegate Expression**
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/957264f1-e72d-41f1-9579-eb9dc00775b8)
Which is a pointer to a service in AppServices as above:
```
service2
```
Or in release 2.0.0: as per #134 
```
 myHelper.Service3
```
Where AppServices looks like this:
```
class AppServices {
   myHelper;
    async service1(input, context) {
        .......
        return someoutput;
    }
 class MyHelper {
    async service2(input, context) {
        .......
        return someoutput;
    }
}
```
**All Delegate Expression methods have same signature (input,context)**

### Execution Listeners
On the other hand, start/end execution listener as just a javaScript with full context passed to the script and have full access to call any method with any signature.

### Run-Time Listener

`AppDelegate` or the invoking code can create a runtime listener
```
    const listener = server.listener;

    listener.on('end', function ({ context, event }) {
        console.log('----->'+event+" "+ context.item.elementId);
    });

    listener.on('all', function ({ context, event, }) {
//        console.log('-----> Event:', event);
    });

    listener.on('wait', function ({ context, event }) {
        console.log('-----> wait 1' + event , context.instance.id,context.item.id);
    });}
```

**Comment by ralphhanna** [comment]
One Question: What is the difference between before/after vs start/end?

**Comment by kstan79** [comment]
> One Question: What is the difference between before/after vs start/end?

start/end only exists in `process`, mean initialize of process or end of the process. (please take note in single bpmn may have multiple start element or multiple end element)

regarding before/after, it only in elements, which is executionListener

**Comment by ralphhanna** [comment]
Please Test this added feature in new release.

https://github.com/bpmnServer/bpmn-web
