### ISSUE TITLE
No camunda formdata in usertask items

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#140]
as examples.md stated camunda form is supported:

![https://github.com/bpmnServer/bpmn-server/raw/master/docs/bb-form.PNG](https://github.com/bpmnServer/bpmn-server/raw/master/docs/bb-form.PNG)

i use same property as examples, define in my user task
```xml
<bpmn:userTask id="Activity_07kqvhs" name="approve1">
      <bpmn:extensionElements>
        <camunda:formData>
          <camunda:formField id="needsRepairs" label="Repairs Required?" type="boolean" />
          <camunda:formField id="needsCleaning" label="Cleaning Required?" type="boolean" />
        </camunda:formData>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1ch6wn0</bpmn:incoming>
      <bpmn:outgoing>Flow_1x9zeai</bpmn:outgoing>
    </bpmn:userTask>
```

after execute workflow and I try to read the form fields, hope I can render a form but I can't obtain any useful info from findItems. 
At frontend UI, we can't know what kind of inputs we want to capture, we rely on camunda form data. Any reference of it?

Thanks,

**Comment by ralphhanna** [comment]
Yes, here is sample code:
    static async getNodeInfo(processName, elementId) {

        let definition = await bpmnServer.definitions.load(processName);
        let node = definition.getNodeById(elementId);
        let extName = Behaviour_names.CamundaFormData;
        let ext = node.getBehaviour(extName);
        let fields;
        if (ext)
            fields = ext.fields;
        return { node, fields };
    }

**Comment by ralphhanna** [comment]
Here is the rest of it:

extends layout

block content

	h3 Invoking Item  #{name} - #{processName}
	p Item Id: #{id}

	h4 Data 
	table
		each v in vars
			tr
				td #{v.key}
				td #{v.value}
	
	table
		form(name='InvokeForm',action="/invokeItem",method="post")
			input(type='hidden',name='itemId',id='itemId',value=`${id}`)

			each field in fields
				tr 
					a(vertical-align="top")

					td #{field.label}
					td  
						if (field['$children'])
							select(name=`${field.id}`)
								each v in (field['$children'])
									option(value=`${v.id}`) #{v.name}
						else if (field.type=='date')
							input(name=`${field.id}` type='date')
						else
							input(name=`${field.id}`)
			tr
				td
					input(type='submit')

**Comment by kstan79** [comment]
ok i found it. thanks! Seems it hide too deep and can't obtain it easily. 

since definition and nodes no type:
```ts
 let definition = await this.bpmnServer.definitions.load(processName);
let node = definition.getNodeById(elementId);
const ext = node.getBehaviour('camunda:formData')

    if (ext){
         const fields = ext.fields;
          return fields
    }else{
      return []
    }
```


in future we create  definitions related method will be goods, such as :
```ts
const approveTask =  this.bpmnServer.definitions.load(processName)
    .getNodeById('elementId1')
const form = approveTask.getCamundaForm()
const fiels = form.getFields()
```

**Comment by kstan79** [comment]
Hm tested but camunda form property quite far from complete properties. In long run we may create a text area and throw jsonschema into it.
