### ISSUE TITLE
Input Parameters in Task

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-server#142]
Hi @ralphhanna 

Do tasks support input parameters other than `Text` type?

I created a simple workflow with a service task which when called will print the input parameters in console.

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/d76e87ab-201f-48a5-a62f-5ab8a579f73a)

```js
async CheckInp(input, context) {
        console.log(input);
    }
```

Output:
```js
{ destination: 'Hello', listVal2: undefined, params: undefined }
```
There are no problem with `Text` fields but all other type of fields return as `undefined`.

Could you kindly look into this? Thanks.

**Comment by ralphhanna** [comment]
Your are write they are not supported at this release, will fix in next Release 2.0.0 in about 1-2 weeks,
If urgent I can rush another release

Thanks

**Comment by MaheshkumarSundaram** [comment]
@ralphhanna 

No rush. 2 weeks should be fine. Thank you.

**Comment by ralphhanna** [comment]
Ok, here is the new implementation (for next release) just to comment on:
### BPMN file
```js
        <camunda:inputOutput>
          <camunda:inputParameter name="text1">data.text1</camunda:inputParameter>
          <camunda:inputParameter name="list2">
            <camunda:list>
              <camunda:value>data.val1</camunda:value>
              <camunda:value>data.val2</camunda:value>
              <camunda:value>data.val3</camunda:value>
            </camunda:list>
          </camunda:inputParameter>
          <camunda:inputParameter name="map3">
            <camunda:map>
              <camunda:entry key="key1">1</camunda:entry>
              <camunda:entry key="key2">2</camunda:entry>
            </camunda:map>
          </camunda:inputParameter>
          <camunda:inputParameter name="list4">
            <camunda:list>
              <camunda:value>"val1"</camunda:value>
              <camunda:value>'val2'</camunda:value>
            </camunda:list>
          </camunda:inputParameter>
          <camunda:inputParameter name="text5">data.objSample</camunda:inputParameter>
          <camunda:inputParameter name="text6">[data.val1,data.val2,data.val3]</camunda:inputParameter>
        </camunda:inputOutput>
```
data object:
```
{
  list1: [ 'a', 'b', 'c' ],
  val1: 'abc',
  val2: 'xyz',
  val3: 'value 3',
  objSample: { x: 1, y: 2, Z: 3 },
  text1: 'my text is here'
}
```
What is being passed to the service:
```
service echo - input {
  text1: 'my text is here',
  list2: [ 'abc', 'xyz', 'value 3' ],
  map3: Map(2) { 'key1' => 1, 'key2' => 2 },
  list4: [ 'val1', 'val2' ],
  text5: { x: 1, y: 2, Z: 3 },
  text6: [ 'abc', 'xyz', 'value 3' ]
}
}
```
### PLEASE NOTE:
1.  Values defined in the model editor are **javaExpressions**, if you want to pass constants you have to use `quotes` like in list4
2.  Input Variables of type text accept any object not only text, so you can actually pass your own list or map into this variable

**Comment by ralphhanna** [comment]
Sorry, Release 2.0.0 and later changes the syntax so ignore previous NOTE
## PLEASE NOTE:

1. Values defined in the model editor are constants IF YOU WANT `javaScript Expressions`, preceed your script with `$`
2. Input Variables of type text accept any object not only text, so you can actually pass your own list or map into this variable

**Comment by ralphhanna** [comment]
Please Test this added feature in new release.

https://github.com/bpmnServer/bpmn-web

Also see warning above

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna,

Could you please clear my doubts regarding the input variables?

In `v1.4.6`, whenever I configure input variables, I explicitly use quotes to avoid them being treated as JS expression.

In the latest release `alpha`, it seems if there are explicit quotes in constants/ simple strings, it gets treated as a part of the string!!!

Suppose, I declare a input variable named `myVar` in the latest release. I am providing the below examples of that input configuration below based on their type as I understand them. 

`myVar` Type| Example Value| |
--- | --- | --- |
Text/String| hello| No explicit quotes needed
JSON/Map| { 'key1':  'val1', 'key2': 'val2' } | No explicit quotes needed
List| [ 'str1', 'str2', 'str3' ] | No explicit quote needed
JS Expression| $data.item.myVar |

Please correct me if there is any mistake in my understanding of configuring input vars in the latest release.

Thanks.

**Comment by ralphhanna** [comment]
I am away from my pc, but I believe that second and third line requires $ symbol

**Comment by MaheshkumarSundaram** [comment]
Yes, while declaring map, list & boolean, $ symbol should precede. I did verify it just now. Thanks.
