### ISSUE TITLE
How to define request scope variable in execution before start/invoke

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#143]
I want to store some http request variable before workflow start or invoke, example
1. headers
2. tenant
3. email and etc
4. tokens 

The variable will change on every http request, if the http request trigger start/invoke of workflow, then we want to use that variable in all delegate.

**Comment by kstan79** [comment]
I not mean to store user data, i mean store some variable in `request scope` or `context`.

I give example of implementation:
1. user1 and user2 call `start()` a new workflow
2. assume the work flow have 3 step or service task, which is "step1", "step2", and "step3".it is long duration task
3. all 3 step perform crud activities in different mongodb collection
4. beforre running step 1, a mongodb transaction started and i wish to pass the mongodb `dbsession` into execution context.
5. in `step1` delegate, record create  under the dbsession successfully (not yet commit)
6. in `step2` delegate, it retrieve the new record,, and do some others thing. It need to use back same `dbsession`from context, else it will get record not found, since not yet commit in mongodb
7. in `step3`, some data quality check, if everyting fine it commit into db, else it roll back, data in step1,step2 back into original

there is lot of similarity lie we put some variable into express's `req` object, then at another block of source code read from `req` again. Just i wish to know what is the proper place of assign it

**Comment by kstan79** [comment]
after some consideration, the delegates shall run under `bpmn` user context, instead of `caller` (invoker or creator). cause modification of database is done by computer, event though intiator is human.  So above request scope variable no longer make sense. 

however, we still need a way to define variables in the execution context,  `data` nor `vars` is not suitable cause the variables can be runtime object

**Comment by kstan79** [comment]
This is under current version or future version?

**Comment by ralphhanna** [comment]
Options passing is under next release, but you can change DataStore now.

**Comment by ralphhanna** [comment]
Yes, it will be this.options

**Comment by kstan79** [comment]
> Yes, it will be this.options
```ts
[
  'server',   'tokens',
  'promises', 'isLocked',
  'uids',     'seq',
  'instance', 'definition',
  'userId',   'worker',
  'item',     'state',
  'action'
]
```
above string array generate by below delegate service. 
```ts
async hello (vars, context){
    console.log("hellohellohellohellor",Object.keys(context))
}   
```

you mean in future options will add `context.options`?  cause I check from `Task.ts` & `Node.ts` there is no `options` available.

**Comment by ralphhanna** [comment]
Upcoming release, shortly:
```
class Execution extends ServerComponent implements IExecution {
    instance: InstanceObject;
    tokens = new Map();
    definition: IDefinition;
    process : Process;
    errors;
    item;
    messageMatchingKey;
    worker;
    userName;
    promises = [];
    servicesProvider;
    isLocked: boolean = false;
    options;
    operation;

```
For Item:
```
class Item implements IItem {
    id;                 
.....
    log(msg) { return this.token.log(msg); }
    get data() { return this.token.data; }
    set data(val) { this.token.appendData(val,this); }
    setData(val) { this.token.appendData(val,this); }
    get options() { return this.token.execution.options;  }
    get context() { return this.token.execution; }
    get elementId() { return this.element.id; }

```
It is passed at runtime,

So you should be able to say,  `this.options` in scripts since this is the item

**Comment by ralphhanna** [comment]
Please Test this added feature in new release.

https://github.com/bpmnServer/bpmn-web

**Comment by ralphhanna** [comment]
Please Test this added feature in new release.

https://github.com/bpmnServer/bpmn-web

**Comment by kstan79** [comment]
tested version 2, the `vars` in item[n] still empty, the instance's `data` still polluted by user task inputs

**Comment by kstan79** [comment]
Below is sample after invoke, `var1` and `vars2` is input during invoke, been merge to `data`. the item's `vars` remain emtpy: 
![sample2](https://github.com/bpmnServer/bpmn-server/assets/1889979/b1e8377b-d035-43ec-a86b-32c81bbc5366)
![sample1](https://github.com/bpmnServer/bpmn-server/assets/1889979/40ac0bc5-3395-4ca6-bcde-29094e2d4563)
