### ISSUE TITLE
Use sqlite for embedding usage

### ISSUE THREAD

**Issue by linonetwo** [bpmnServer/bpmn-server#145]
Now from readme, it seems a mongodb is required. But when use in an embedded situation like Electron offline first app, maybe a simpler storage will be better.

**Comment by ralphhanna** [comment]
Yes it is possible and has been done, you just have to replace the DB driver class with one of your own.

**Comment by linonetwo** [comment]
I see, it requires writing a custom sqlite class like `class DataStore extends ServerComponent  implements IDataStore`

**Comment by linonetwo** [comment]
![图片](https://github.com/bpmnServer/bpmn-server/assets/3746270/dacaa075-44cb-4679-b7c2-6cb719efe3f5)

The type here should allow SQLite

**Comment by ralphhanna** [comment]
Assuming that you have the following:
```js
class SQLite extends DataStore {
.... your code here
}

```
in the configuration.ts file
```js
var configuration = new Configuration(
	{
...
		database: {
			MongoDB:
			{
				db_url: process.env.MONGO_DB_URL  //"mongodb://localhost:27017?retryWrites=true&w=majority",
			},
			SQLite: { db_connection: '' }
		},
...
		dataStore: function (server) {
//			return new DataStore(server);
			return new SQLite(server);
		},
...		
	});
```

Please keep in mind that you need to have the following tables in SQLite
- wf_instances
- wf_items
- wf_model_events
You probably don't need: 
- wf_locks
- wf_models

**Comment by linonetwo** [comment]
@ralphhanna for

> The type here should allow SQLite

I mean #148

**Comment by linonetwo** [comment]
well, I'm asking GPT to write it, I will PR here if I make it work.

**Comment by linonetwo** [comment]
Seems there are many dependency that should be external, 

```
connect-mongo
@sendgrid/mail
MongoDB
mongoose
```

and some deps make it not available in browser env

```
chalk
```

Will you consider move some deps to another package, like `bpmn-server-mongodb`? This will make it optional, and useable in the browser env (with some remote db connector or indexeddb driver, or a tiddlywiki driver for store data in the wiki)

**Comment by linonetwo** [comment]
I'm planning to embed this as a plugin in tiddlywiki, so it can execute AI workflow in this browser based notebook. (And execute on nodejs side if user is in client-server setup)

And at principle, bpmn engine don't really need to rely on nodejs. I can use bpmn-client to connect to a server in web worker, if user is in pure browser env, and connect to nodejs side server, if user is using nodejs version of tiddlywiki.

**Comment by ralphhanna** [comment]
This is correct, bpmn-client is very light weight, but needs to connect to a bpmn-server install on the cloud.

Thanks

**Comment by linonetwo** [comment]
Are you working on this? Will it be possible to run in pure JS env later? (no nodejs or browser API, for example, webworker or blueberry pie)

I'm not sure how this will be done, but do you need me to do something?

**Comment by ralphhanna** [comment]
Please go ahead if you can, bpmn-client is stable, no changes for now. It requires a bpmn-server you can use bpmn.omniworkflow.com as a server
change .env to:
```
API_KEY=12345
HOST=bpmn.omniworkflow.com
PORT=443
BASE_URL=api
```

Thanks very much, and please let me know if you need help

**Comment by ralphhanna** [comment]
can we close this now?

**Comment by linonetwo** [comment]
Yes, I decided to use Tiddlywiki as storage now. And I know I can now.
