### ISSUE TITLE
Import Error through client

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-server#154]
Hi @ralphhanna 

Test Version: 1.4.6

I am using `bpmn-client` to import a new BPMN into the server.

But I get the following error:

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/95e87df6-1ad8-430e-a28e-ce8947f160cb)

Import used to work fine. Could you please look into this? Thanks

**Comment by ralphhanna** [comment]
Sorry, seems to work for me, can you look at the server console log.
It is a server error

**Comment by MaheshkumarSundaram** [comment]
@ralphhanna 
In the server console, I get this:

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/ccc8981d-9c81-4dca-8c5d-a48043420cfb)

**Comment by ralphhanna** [comment]
Looks something is invalid in the bpmn file, can you please send it to me @ ralphhanna@hotmail.com 
Thanks,
Ralph

**Comment by MaheshkumarSundaram** [comment]
> Looks something is invalid in the bpmn file, can you please send it to me @ [ralphhanna@hotmail.com](mailto:ralphhanna@hotmail.com) Thanks, Ralph

@ralphhanna, I have emailed you the files. Thank you

**Comment by ralphhanna** [comment]
Got it, just remove two lines the includes the word 'class=""'
lines 127 and 154
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/fe4f8893-5e39-46a4-a147-47be48f1929f)

**Comment by MaheshkumarSundaram** [comment]
Ah sorry. Thank you so much @ralphhanna.
