### ISSUE TITLE
How to do task listener in rel2..0.0?

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#157]
> Task listeners: only for User Tasks, , fires JavaScripts defined at the model
> assign: invoked on invoke and assign commands
> validate: invoked on invoke and assign commands

According previous discussion it will have task listener, I'd tried to implement it but run time error. From the `Task.ts` I didn't notice any code implementing the task listener. Is it available? Or shall I implement it with method similar like `service task delegates` and send PR?

**Comment by kstan79** [comment]
seems i need to listen from server?
```ts
this.bpmnServer.listener.on('all',(event)=>{
      console.log("-----------------------------------------")
      if(event.context.item){
        const workflowName = event.context.instance.name
        switch(event.context.item.element.type){
          case 'bpmn:UserTask':
            console.log("Process: ", workflowName,", event ",event.event)
            if(event.event=='end')this.sendDelegates('complete',event)
            else if(event.event=='start') this.sendDelegates('create',event)
            //others
          break;
          case 'bpmn:ServiceTask':
            // console.log(workflowName,event.event)
            // this.sendDelegates(event)
          break;
        }
      }
      
    })
}
```

**Comment by kstan79** [comment]
if above method is appropriate, I would like to suggest remove existing way of servicetask  delegate approach, all standardise using listener. It help you make project much easier:
1. you only need to concentrate polish content in listener
2. single entry point of all events, everybody can understand and track
3. documentation won't become messy, different element different document

**Comment by kstan79** [comment]
seems only at below configuration then able to get `invoke's input`:
```ts
event.context.item.element.type: 'bpmn:UserTask',
event.event: 'transformInput'

the input store at `context.item.input`
```

**Comment by ralphhanna** [comment]
Task listener is already implemented in your code above.
Also here is another code example:
```
    api.server.listener.on('all', async function ({ context, event, }) {
        if (event=='process.restored')
            {
            context.options=options;
            context.options['restored']=true;
            }
        if (event.startsWith('process.'))
            console.log('---Event: -->' + event , context.options);
        else 
            console.log('---Event: -->'+event, 'item:',context.item.elementId,context.options );
    });


```
As a result here is the output:
```
---calling start-----
---Event: -->      process.start
---Event: -->StartEvent_1     transformInput
---Event: -->StartEvent_1     enter
---Event: -->StartEvent_1     start*
---Event: -->      process.saving
---Event: -->StartEvent_1     end*
---Event: -->Request     enter
---Event: -->Request     start*
---Event: -->Request     wait
---Event: -->      process.wait
---Event: -->      process.saving

---calling assign-----
---Event: -->      process.restored
---Event: -->Request     assignment*
---Event: -->      process.saving

---calling invoke-----
---Event: -->      process.restored
---Event: -->      process.invoke

---Event: -->Request     transformInput
---Event: -->Request     end*

---Event: -->Approve     enter
---Event: -->Approve     start*
---Event: -->boundaryEvent     enter
---Event: -->boundaryEvent     start*
---Event: -->boundaryEvent     wait
---Event: -->Approve     wait
---Event: -->      process.invoked
---Event: -->      process.saving

* Only start/end	have execution listeners/assignment
* Only assignment 	have a task listener
```
No need for additional listeners

**Comment by ralphhanna** [comment]
Sorry, above list is from old release: here is the latest:
```
---Event: -->process.start { option1: 1234 }
=========== Process Start ===============

---Event: -->transformInput item: StartEvent_1 { option1: 1234 }
---Event: -->enter item: StartEvent_1 { option1: 1234 }
---Event: -->start item: StartEvent_1 { option1: 1234 }
---Event: -->process.saving { option1: 1234 }
---Event: -->end item: StartEvent_1 { option1: 1234 }
---Event: -->enter item: Request { option1: 1234 }
---Event: -->start item: Request { option1: 1234 }
---Event: -->wait item: Request { option1: 1234 }
---Event: -->process.wait { option1: 1234 }
---Event: -->process.saving { option1: 1234 }

---calling assign-----

---Event: -->process.restored { option1: 1234, restored: true }
---Event: -->assign item: Request { option1: 1234, restored: true }
---Event: -->validate item: Request { option1: 1234, restored: true }
---Event: -->process.saving { option1: 1234, restored: true }

---calling invoke-----

---Event: -->process.restored { option1: 1234, restored: true }
---Event: -->process.invoke { option1: 1234, restored: true }
---Event: -->transformInput item: Request { option1: 1234, restored: true }
---Event: -->validate item: Request { option1: 1234, restored: true }
---Event: -->end item: Request { option1: 1234, restored: true }
---Event: -->enter item: Approve { option1: 1234, restored: true }
---Event: -->start item: Approve { option1: 1234, restored: true }
---Event: -->enter item: Event_1lkpj3z { option1: 1234, restored: true }
---Event: -->start item: Event_1lkpj3z { option1: 1234, restored: true }
---Event: -->wait item: Event_1lkpj3z { option1: 1234, restored: true }
---Event: -->wait item: Approve { option1: 1234, restored: true }
---Event: -->process.invoked { option1: 1234, restored: true }
---Event: -->process.saving { option1: 1234, restored: true }

---invoke Approve-----

---Event: -->process.restored { option1: 1234, restored: true }
---Event: -->process.invoke { option1: 1234, restored: true }
---Event: -->transformInput item: Approve { option1: 1234, restored: true }
---Event: -->validate item: Approve { option1: 1234, restored: true }
---Event: -->process.error { option1: 1234, restored: true }
***************BPMNServer UNCAUGHT ERROR***********

Error Message: Error: Validation failed with error:Not a valid value

In addition:
---Event: -->      process.invoked
---Event: -->      process.saving
```

**Comment by ralphhanna** [comment]
Regarding your point about `Service Task`s , solution very simple, just leave the implementation and delegate name blank
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/c7f4039d-4893-40b1-8d55-ab35379ae701)

it will go to appDelegate.serviceCalled:
```
    async serviceCalled(input, context) {
        this.server.logger.log("service called");
        console.log('service called', input, context.item.node.name);
    }
```

**Comment by kstan79** [comment]
There is run time error after add task listener delegate. you may check images at below. The event type i tried included `complete` or `assign`: 

![tasklistenererror](https://github.com/bpmnServer/bpmn-server/assets/1889979/caf9f136-3d70-4eda-a374-58b584fb3fd6)

This issue not exists before I apply task listener. Is it this properties not allowed?

**Comment by kstan79** [comment]
I wish to send warm remind to update document, when wish to obtain user input during invoke, need filter event filter:
```
1. event.type: `transformInput`
2. element.type ='bpmn:UserTask' 
```
So far I can't find others event suitable, `process.invoke` & `process.invoked` doesn't supply attribute `item` and no way to access `input`

**Comment by kstan79** [comment]
run time errors seems can solve from #159

**Comment by ralphhanna** [comment]
1. Can you please try this in bpmn.io?
2. What bpmn editor are you using.
3. Not aware of `complete` we have 'end' instead
4. I strongly recommend follow standard bpmn by using **delegate expression**

**Comment by ralphhanna** [comment]
Input is available in `start` event.

See code below:
```
---calling start-----
UserService.init()
---Event: -->process.start { option1: 1234 }
---Event: -->transformInput item: StartEvent_1 { option1: 1234 }
---Event: -->enter item: StartEvent_1 { option1: 1234 }
---Event: -->start item: StartEvent_1 { option1: 1234 } input: { reason: 'I like it', type: 'Vacation' }
---Event: -->process.saving { option1: 1234 }
---Event: -->end item: StartEvent_1 { option1: 1234 }
---Event: -->enter item: Request { option1: 1234 }
---Event: -->start item: Request { option1: 1234 } input: {}
---Event: -->wait item: Request { option1: 1234 }
---Event: -->process.wait { option1: 1234 }
---Event: -->process.saving { option1: 1234 }
---calling assign-----
---Event: -->process.restored { option1: 1234, restored: true }
---Event: -->assign item: Request { option1: 1234, restored: true }
---Event: -->validate item: Request { option1: 1234, restored: true }
---Event: -->process.saving { option1: 1234, restored: true }
---calling invoke-----
---Event: -->process.restored { option1: 1234, restored: true }
---Event: -->process.invoke { option1: 1234, restored: true }
---Event: -->transformInput item: Request { option1: 1234, restored: true }
validating Request
---Event: -->validate item: Request { option1: 1234, restored: true }
---Event: -->end item: Request { option1: 1234, restored: true }
---Event: -->enter item: Approve { option1: 1234, restored: true }
---Event: -->start item: Approve { option1: 1234, restored: true } input: {}
---Event: -->enter item: Event_1lkpj3z { option1: 1234, restored: true }
---Event: -->start item: Event_1lkpj3z { option1: 1234, restored: true } input: {}
---Event: -->wait item: Event_1lkpj3z { option1: 1234, restored: true }
---Event: -->wait item: Approve { option1: 1234, restored: true }
---Event: -->process.invoked { option1: 1234, restored: true }
---Event: -->process.saving { option1: 1234, restored: true }
```

**Comment by kstan79** [comment]
Yes I aware start input exists at transformInout event too, just i particular highlight invoke too. I believe others people will have same confusion too.

**Comment by ralphhanna** [comment]
Invoke is a command not an listener event
Also validate should have input
Sent from my iPhone

On Dec 17, 2023, at 7:28 PM, Ks Tan ***@***.***> wrote:

﻿

Yes I aware start input exists at transformInout event too, just i particular highlight invoke too. I believe others people will have same confusion too.

**Comment by bpmn-ts** [comment]
Sorry don’t understand Can you show your calling codeSent from my iPhoneOn Dec 17, 2023, at 7:33 PM, ralphhanna ***@***.***> wrote:﻿
Invoke is a command not an listener event

Also validate should have input

Sent from my iPhone



On Dec 17, 2023, at 7:28 PM, Ks Tan ***@***.***> wrote:



﻿



Yes I aware start input exists at transformInout event too, just i particular highlight invoke too. I believe others people will have same confusion too.

**Comment by kstan79** [comment]
its ok, im continuing evaluate version, i think we have to redesign document from the ground up, start from introduction until integrate into specific framework. the current readme have info, some is not up to date, or no cover important aspect

**Comment by ralphhanna** [comment]
I am still waiting for some feedback, including yours and working on documentation, yes from the ground up, once ready will go into master. 
Currently, all development and testing work is done, unless new issues come up
Thanks

**Comment by kstan79** [comment]
I'd tested using listener seems working well with below:
1. use rel2.0.5-alpha2 + changes in #159  
2. stop use all app deligates 
3. use event/listener instead to capture event

If possible please release npm 2.0.6-aphaX with  patch of #159 cause it is difficult for me to test in my project. You  may close this thread after release #159 into npm.

**Comment by ralphhanna** [comment]
```
npm notice === Tarball Details ===
npm notice name:          bpmn-server
npm notice version:       2.0.5-alpha2.0
npm notice filename:      bpmn-server-2.0.5-alpha2.0.tgz
npm notice package size:  117.1 kB
npm notice unpacked size: 637.6 kB
npm notice shasum:        fbcfec6cb5e2c4a50639a6c1492443af1bf04cb5
npm notice integrity:     sha512-EQUkWgm/g2h4w[...]N1B8JotPqZpDA==
npm notice total files:   206
npm notice
npm notice Publishing to https://registry.npmjs.org/
+ bpmn-server@2.0.5-alpha2.0
```

Please explain **stop use all app deligates** ?

**Comment by kstan79** [comment]
This is new publish include the fix?

Regarding stop all delegates, previously my design will load user task and service task delegates property and create suitable method for execution. Now all method name generate using elementid

**Comment by ralphhanna** [comment]
Yes latest release includes the fix

**Comment by kstan79** [comment]
Ok tq

**Comment by kstan79** [comment]
ops, no this npmn publish `bpmn-server@2.0.5-alpha2.0` doesn't include the patch in `dist`:

the build `dist/elements/Definition.js` content:
```ts
... //others codes
loadProcess(definition, processElement, parentProcess) {
        const children = [];
        const process = new _1.Process(processElement, parentProcess);
        if (processElement.extensionElements) {
            processElement.extensionElements.values.forEach(ext => {
                let scripts = [];
                var scrs = ext['$children'];
... //others codes
```

**Comment by ralphhanna** [comment]
ops, it is there in src but not dist, sorry bit confused about new layout
till I figure it out, new release is coming shortly, but for now 
can you just run 
tsc --build

**Comment by ralphhanna** [comment]
Done please check

**Comment by ralphhanna** [comment]
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/bf62d034-1f87-4ca5-994c-f1a3196d3fd1)

**Comment by kstan79** [comment]
Ok seems the code appear in my computer too.
