### ISSUE TITLE
V2.0 User task data still polluted by invoke input

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#164]
I notice version 2.0 the data still modify by invoke input. As discussed before this shouldn't as default behavior

**Comment by ralphhanna** [comment]
Yes, I know, I thought you mentioned that you want an update function as well.

If you pass empty object for data, no update will take place,same for assignment

**Comment by kstan79** [comment]
I thought transformInput obtain inputs from data? If not use data what
other place I can obtain the actor input?

Thank you very much.

Best Regards,
KS Tan

*SIM IT SDN. BHD.* (792899-U)
20, Jalan Ekoperniagaan 2/5, Taman Ekoperniagaan,
81100. JB Johor. Malaysia.
Office Tel/Fax: +6(07) 863 7089
Office Mobile: +(60)19 776 0680 +(65)9323 0628
Email: ***@***.***

Corporate Website:
http://www.simitgroup.com
http://www.onlinesimbiz.com
http://www.simtrainsystem.com
http://www.simsalonsystem.com

~ Because of you, we are here ~

*CONFIDENTIALITY NOTICE:* The information in this document may be
confidential. It is intended only for the use of the named recipient. If
you are not the intended recipient, please notify us immediately and then
delete this document. Do not disclose the contents of this document to any
other person, nor take any copies. Violation of this notice may be
unlawful. Also note, the opinions expressed in this document are those of
the author, and not necessarily those of SIM IT SDN. BHD.

**Comment by kstan79** [comment]
I thought the invoke process trigger transformInput, and only 'data' can use. When use data the instance data polluted.

**Comment by kstan79** [comment]
for example, during `event tranformInput`,  user submited input as `{ b: 11199 }`, and data initially as  `{ aaa: 2222, tenantId: 1, orgId: 1, branchId: 1 }`. Sample of my workflow process property similar as below: 
```ts
{
  workflowName: 'suspendcustomer',
  eventType: 'invoked',
  elementType: 'bpmn:UserTask',
  elementId: 'approve1',
  elementName: 'approve1',
  elementProps: {
    startedAt: 2023-12-21T15:28:39.544Z,
    assignee: 'kstan',
    candidateGroups: null,
    candidateUsers: null,
    dueDate: null,
    followUpDate: null,
    priority: null,
    formKey: 'simpleapprove'
  },
  usertaskinput: { b: 11199 },
  data: { aaa: 2222, tenantId: 1, orgId: 1, branchId: 1 },
  options: {}
}
```
afterwards, the `usertaskinput` been merge into data become: 
```ts
{
aaa: 2222
tenantId: 1,
orgId: 1,
branchId: 1,
b: 11199
}
```

as mentioned, we need `invoke` submit input data, that is purely the actor input and it `SHOULD NOT ASSUME AS PART OF DATA AND IT WILL MESS THE DATA`. 

previously we discussed, store user's input into `vars` as alternative in `invoke` but it seems not yet implemented.  I'm ok to implement it and send PR, just need to get conclusion for go ahead.

**Comment by ralphhanna** [comment]
Please try the following logic:
1. User provides input data, let us call it 'formData', {field1:val1,field2:val2}
2. Your app calls ```api.engine.invoke({...},formData,....); ```
3. Inside the model, you have a listener `validate`
```js
item.vars.field2=item.input.field2;
delete data.field2;
```
4. Now look at data:
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/f992f404-9283-4dee-98a8-0a4211d1703e)

![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/c51ca76d-4eca-4af8-a94e-a0e45eee81a8)

I hope this is what you are looking for.

p.s. `transformInput` is used only for `serviceTasks`

Thanks

**Comment by kstan79** [comment]
Ok it seems can solve my problem.

However it is kind of hack, if every task added new properties in form data, we have to remember remove it. 

Is there any place I can off merge invoke input into data?

I will try to implement it and send pr

**Comment by ralphhanna** [comment]
Let me think about it
Sent from my iPhone

On Dec 21, 2023, at 7:45 PM, Ks Tan ***@***.***> wrote:

﻿

Ok it seems can solve my problem.

However it is kind of hack, if every task added new properties in form data, we have to remember remove it.

Is there any place I can off merge invoke input into data?

I will try to implement it and send pr

**Comment by ralphhanna** [comment]
Ok, this should it without any code modifications to `bpmn-server`

In the AppDelegate class:
```ts
    async executionEvent(context, event) {

		if (event == 'transformInput') {
			
			// Move input to item.vars
			context.item.vars = JSON.parse(JSON.stringify(context.item.input));
			// remove input before system copies it instance.data
            context.item.input = {};
		}
```
This will change behaviour for all of your models, now input from users goes to `item.vars` instead of `instance.data`.

The challenge with that, you made it difficult for tasks to talk to each other. not easy to say:
```
getItemForTask(item,taskId) : IItem {
const items=item.token.execution.getItems();
// run a filter

}
``` 
Since sometimes, for good reason, there could be multiple items for 'Request' Task.
But you can write a method in appServices or appUtils to

**Comment by kstan79** [comment]
Thanks, I will try it and feed back if necessary.

**Comment by kstan79** [comment]
> ```ts
> executionEvent
> ```

no luck, I'd tried console something in`executionEvent()` but it seems no executed.

**Comment by kstan79** [comment]
The workable approach is implement at listener, copy property over. and set `input = {}`.

**Comment by ralphhanna** [comment]
both `instance.data` and `item.vars` are persistent.
`item.input` and item.output` are not

**Comment by kstan79** [comment]
I mean I'd transferee value from input to vars but not persist, while listener

**Comment by ralphhanna** [comment]
What do you want to do with values the user has input?

**Comment by kstan79** [comment]
Very basic requirement, assume there is multiple step approval, each approval have comment. We want to keep the comment and display at frontend.

**Comment by ralphhanna** [comment]
Are these steps in a different task or the task is repeated?

there several ways to do
1 store in instance.data in different variables 
2 in data as array 
3 each in item.vars

but in all cases it must be saved in database

**Comment by ralphhanna** [comment]
All workflows are db bound
They are loaded into memory and destroyed after between steps

so you can shutdown the server and no data is lost

**Comment by kstan79** [comment]
Yes, I mean I'd copy the value into 'item.vars', but it not save into database

**Comment by ralphhanna** [comment]
If you don’t save them in db, how are you going to display to the user later, say in few days?

if you don’t want to save data, just don’t copy to item.vars

**Comment by ralphhanna** [comment]
Sorry did I misunderstand you?
Are you saying that item.vars didn’t save? As it should?

if this is the case please send me your code
Thanks

**Comment by kstan79** [comment]
Yes, base on our previous conversation bpmn server shall persist vars in db by itself, without any modification. Currently it not persist it.

**Comment by ralphhanna** [comment]
Can you please attach your sample code and model, because this works for me
