### ISSUE TITLE
How does the scalability feature work?

### ISSUE THREAD

**Issue by mramin2000** [bpmnServer/bpmn-server#166]
Hello,

how does the scalability feature work? I like to have multiple servers running with one mongo db. How can I achieve this? I have seen that the current version of the server uses the env "SERVER_ID" together with the database collection "wf_locks". Can you provide more details about this feature or is there a documentation for this?

Thank you very much!

**Comment by ralphhanna** [comment]
Hi
Scalability feature works out the box, no additional action on your part.

-  define servers pointing to same MongoDB
- set SERVER_ID to unique values for each server
- Only one server should have CRON (timers on), others should be:
```
const server = new BPMNServer(configuration, logger,{cron:false});

```
## Concurrency Implementation
- Workflow instances are database bound; retrieved and saved all the time
- Before retrieving the instance, a lock is issued against it in collection `wf-locks`
- After execution of an instance is complete and data is saved, lock is released.
- This to ensure only one operation can be performed against the workflow at any time, other operations will have to wait for the lock to be released.
- The scope of the lock is the workflow instance only, other instances of same model or different models can still be executed
