### ISSUE TITLE
Loading model  Error when there is Lane without activity

### ISSUE THREAD

**Issue by ingpconci** [bpmnServer/bpmn-server#167]
When there is a Lane without Task

![image](https://github.com/bpmnServer/bpmn-server/assets/8488830/8646eac3-4138-4f69-ad51-429c42fcbf9e)

<bpmn:lane id="Lane_0o2ugtd" name="Research Unit New User" />

The error is in the Definition.ts row 107

`
***************BPMNServer UNCAUGHT ERROR*********** TypeError: Cannot read properties of undefined (reading 'forEach')
    at ...\PUBLIC_loopback4-bpmn-server\node_modules\bpmn-server\src\elements\Definition.ts:107:34 
`

`        processElement.laneSets.forEach(ls=>{
           ls.lanes.forEach(lane=>{
                    lane.flowNodeRef.forEach(fnr=>{
                            let target = this.getNodeById(fnr.id);
                            target.lane=lane.name;
                        });
                });
            });
        }
`

To solve :
`
                if (lane.flowNodeRef) { 
                }
`

**Comment by bpmn-ts** [comment]
Thanks will fix in new release Sent from my iPhoneOn Jan 11, 2024, at 11:28 AM, ingpconci ***@***.***> wrote:﻿
When there is a Lane without Task
image.png (view on web)
<bpmn:lane id="Lane_0o2ugtd" name="Research Unit New User" />
The error is in the Definition.ts row 107
***************BPMNServer UNCAUGHT ERROR*********** TypeError: Cannot read properties of undefined (reading 'forEach') at ...\PUBLIC_loopback4-bpmn-server\node_modules\bpmn-server\src\elements\Definition.ts:107:34 
       processElement.laneSets.forEach(ls=>{ ls.lanes.forEach(lane=>{ lane.flowNodeRef.forEach(fnr=>{ let target = this.getNodeById(fnr.id); target.lane=lane.name; }); }); }); }
To solve :
if (lane.flowNodeRef) {  }

**Comment by ralphhanna** [comment]
Fixed in new Alpha Release
