### ISSUE TITLE
Condiitonal Expression

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-server#170]
Hi @ralphhanna,

Conditional Expression evalution seems to be wrong.

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/10dcff00-d359-4383-99ce-5e82380d1904)

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/6473dbdc-50a0-4049-9c05-00d2d5e8e462)

In my `appServices.ts`, I have the below:

```js
async TestServiceCall(input, context) {
        const { isAbort } = input;
        if (isAbort === '0') {
            context.item.data.ErrorCode = null;
        } else {
            context.item.data.ErrorCode = 'Abort';
        }
    }
```

Result:

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/c01924f1-7bfa-4c13-9f58-bb783096c60e)

**Although the condition is not true, it's taking the wrong flow path.**

Please look into this? Thanks.

**Comment by ralphhanna** [comment]
What release are you using
In 2.0.0 you need to add $ in condition

**Comment by MaheshkumarSundaram** [comment]
Ah alright @ralphhanna. 
Is `$` symbol required in front of `start` or `end` inline scripts in `Execution Listeners` too as they are JS expressions?

**Comment by ralphhanna** [comment]
As a result of your question, I had a change of mind!!!!
Sorry, It looks much simpler not to add '$' for condition and others that are explicit JavaScripts
'$' is only required for:
- Assignment Attributes, that can be simple strings or scripts (with $)
- Loop values
- Input/Output values of types Text

Please see https://github.com/bpmnServer/bpmn-server/blob/rel2.0.0/docs/scripting.md and review
Awaiting your feedback
Thanks

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna,

>> Sorry, It looks much simpler not to add '$' for condition and others that are explicit JavaScripts

I agree. The document seems nice which covers all the usecases.

Just to clarify on [your example for Input/Output](https://github.com/bpmnServer/bpmn-server/blob/rel2.0.0/docs/scripting.md#inputoutput), now the latest version supports all types of Input/Output -> `Text`, `List`, `Map` & `JavaScript` explicitly instead of using `Text` for all types. Am I right?

Thanks.

**Comment by MaheshkumarSundaram** [comment]
@ralphhanna Following the above, I tested these recent changes.

I don't see any problems with functionalities. But there is a very minor issue when displaying the instance details.

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/145c7b29-185a-4fce-8142-ade18d902072)

Although I provided key/value pairs for the `Map` variable in the model, the instance details doesn't display it while all other types of data get displayed properly.

![image](https://github.com/bpmnServer/bpmn-server/assets/55505611/605ca7b3-a929-4c84-9c39-2ae1f1e542f2)

Thanks.

**Comment by ralphhanna** [comment]
Correct, new release support all allowed types list,map,text and Script
Thanks for noticing it,
JSON.Stringify does not support map, so now I use array, here is the result

![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/a61f553c-f5ee-4b7b-81ce-f459e1abe3b5)

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna, 
I don't think the last two commits by you are reflected in the [`npm` package](https://www.npmjs.com/package/bpmn-server?activeTab=versions). 
Could you please verify this? Thanks.

**Comment by ralphhanna** [comment]
Done,
Thanks
