### ISSUE TITLE
Which API can be used to implement the functionality of returning to the previous node? 

### ISSUE THREAD

**Issue by magicmayu** [bpmnServer/bpmn-server#177]
Taking "Buy Used Car" as an example, when reaching the "Drive" node, the mechanic discovers a malfunction that has not been completely repaired and needs to go back to the "Repair" node. 
Which API should be used to handle this situation?

**Comment by ralphhanna** [comment]
Hi @magicmayu 

Please see detailed discussion https://github.com/bpmnServer/bpmn-server/discussions/175

Current Release 2.1.0 support `engine.restart` for completed instance, i.e., after "Drive" task is completed. It is rather difficult to return to a task while instance is still run because it may conflict with other running tasks (like timers, receive events, etc.).

In Short:
```ts
api.engine.restart(query,data,options);
```

**Comment by magicmayu** [comment]
i'm sorry that i answered late.
But restart can't cover my case.
![image](https://github.com/bpmnServer/bpmn-server/assets/16733993/7e1cf0cd-e988-4b02-b458-1cbee86cbe84)
In this simple approval process, for example:
1. Tom start a new approval process instance. The instance will  change to status like this.
![image](https://github.com/bpmnServer/bpmn-server/assets/16733993/a1b120f4-efd2-46dd-8149-8ed4ed186ded)
2. when he waiting for his leader's approval, he find it he make a mistake and want to correct it.
How to make the instance to go back to status like this
![image](https://github.com/bpmnServer/bpmn-server/assets/16733993/bc681f2f-c32e-4645-8aef-1d5a09da8797)
Also if Jack approves Tom's ask, when he waiting for CEO Jonh's approval, he maybe want to recall his dicission too.

In my enterprise, this is a general case.
Or how can I modify my flowchart to complete this case?
This is the first time i use process engine, hope for your help? @ralphhanna

**Comment by ralphhanna** [comment]
You may try something like this:

![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/6c7696f9-e7fa-4d26-883a-bb1d9523e529)
[Cancel Application 2.zip](https://github.com/bpmnServer/bpmn-server/files/14567093/Cancel.Application.2.zip)

**Comment by ralphhanna** [comment]
a cleaner version is available here https://bpmn.omniworkflow.com/model/edit/Cancel%20Application

**Comment by magicmayu** [comment]
> a cleaner version is available here https://bpmn.omniworkflow.com/model/edit/Cancel%20Application

Thank you for your answer, it inspired me a lot。
