### ISSUE TITLE
Tasks of multi-instance SubProcess do not know their associated data value

### ISSUE THREAD

**Issue by kvdinker** [bpmnServer/bpmn-server#178]
Hi,

I´m currently working on a workflow with multi-instance subprocesses, where we have some usertasks inside the subprocess which need to access their associated collection value. But unfortunately I only find one subprocess related object with all values in the datastore and no key that tells which element belongs to the current subprocess.

![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/d0e062a5-4147-4b59-a7bc-f805cd68bc57)

Is there any way to access the subprocess related value?

Setup:  
- Bpmn-web as initial backend implementation 
- A separate custom nextjs UI 
- Both connected with bpmn-client as rest-api

If you need further information, let me know.
Thanks

**Comment by ralphhanna** [comment]
Can you please attach your model bpmn file,
Thanks

**Comment by ralphhanna** [comment]
Thanks for your submission, a fix is on the way the correct data structure should be:
```json
departments:  ["IT","HR","Billing"]
department :{
"0":{"loopKey":"IT","vote":"v1","additionalInformation":"ai1"},
"1":{"loopKey":"HR","vote":"v2","additionalInformation":"ai2"},
"2":{"loopKey":"Billing","vote":"v3","additionalInformation":"ai3"}
}


```
Where 'v1','v2','v3' is what I entered in the user prompt.

I expect new release later this week.

Thanks

**Comment by kvdinker** [comment]
Thanks for the quick solution.
How do I recognize which task is responsible for which department? All department objects are contained in the IItemData of the individual tasks.

In the same example, I have seen that the main workflow continues to run when a subprocess is completed and the process has not waited for all subtasks. Is it due to a misconfiguration of the bpmn file or how can I achieve this behavior?
![image](https://github.com/bpmnServer/bpmn-server/assets/162983366/6e0494b1-397a-4d54-b7f8-c9537df2224f)

**Comment by ralphhanna** [comment]
New Release 2.1.5 is now ready.
Please see https://github.com/bpmnServer/bpmn-server/blob/master/docs/examples/loop.md for details about loops
