### ISSUE TITLE
Serialize data error during start workflow

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#181]
I'm using latest bpmn server in nestjs, so far it work well. however, I notice sometimes start new workflow bpmn server return json error. At some troubleshooting then notice that when I submit mongoose query result into 'data' this error will happen.

I'm suggest do some typescript control like data validation/submit generic during startworkflow to prevent random error.

**Comment by ralphhanna** [comment]
Thanks @kstan79 
Please give me some examples or ideas of what to validate?

**Comment by kstan79** [comment]
I sugest some of the below method:

1. put serialize and unserialize inside `start`
```ts
const data=JSON.parse(JSON.stringify(data)) 
bpmnServer.engine.start(workflowName, data,....)
```
2. use generic:
```ts
const data : MyType = {...}
bpmnServer.engine.start<MyType>(workflowName, data,....)
// then, in start() scan through `data` to verify any unaccepted property name or type like "function" or etc
```

**Comment by ralphhanna** [comment]
Done in latest release 2.1.11
