### ISSUE TITLE
Off logger

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#182]
I still cant find way to stop log as #133

seems 2nd property of init bpmnServer require ilogger, so I obtain ilogger from  config setting which as below

Itried define config 
```ts
{...,
  logger: function (server) {
        const logger = new Logger()        
        return logger;
      },
...}
```

all console disappear but i get this error
![logger](https://github.com/bpmnServer/bpmn-server/assets/1889979/4790ef53-61a2-489f-aec5-e24294ae32de)

I wish to completely off the bpmn server log from .env, is it supported?

**Comment by ralphhanna** [comment]
Can you please share your project where this happens, I like to debug it for you

**Comment by kstan79** [comment]
thanks! due to your previous repo seems something inside so I created another dummy repo for it [here](https://github.com/kstan79/bpmn-server-innest)

It is dummy project for  demonstration, the user service been commented due to it rely on sso/keycloak.

**Comment by kstan79** [comment]
i finally solve initiate new illogger class and define at constrctor

```ts
class mylogger implements  ILogger{
      setOptions(){}
      clear(){}
      get(){ return [] as any[]}
      debug(){}
      warn(){}
      reportError(){}
      async save(filename:any){}
      log(){}
      error(){}
    }
    this.bpmnServer = new BPMNServer(this.workflowconfig.getConfig(), new mylogger());
```
