### ISSUE TITLE
Loop Instance

### ISSUE THREAD

**Issue by lichiabc** [bpmnServer/bpmn-server#195]
Encountering an issue where, upon utilizing parallel processing,According to the workflow, there may be situations where the item order is reversed.This will cause some issues for the subsequent progress.Your assistance is greatly appreciated.
![image](https://github.com/bpmnServer/bpmn-server/assets/166492661/bebc49aa-f83e-4db2-9551-48f5f813c194)

**Comment by ralphhanna** [comment]
You control the order of execution through the `sequence flow`.
If you want Item 10 ahead of 11, re-arrange the flow sequence

**Comment by shuinan** [comment]
For example, in the current node 11, there are three parallel tasks, and I have set conditions such that upon completion of all tasks, they proceed to the subsequent node. However, currently, one of the parallel processing nodes has advanced to the subsequent node out of sequence. How should the order be adjusted specifically? The BPMN file is the same as that in issue 193.

**Comment by ralphhanna** [comment]
I am sorry, I don't see the problem?
please look here
https://bpmn.omniworkflow.com/instanceDetails?id=0f94a582-4500-4873-8623-d37085f0ffad
Process waited till all items were processed before proceeding to next

**Comment by ralphhanna** [comment]
I am going ahead and close this one
