### ISSUE TITLE
The itemkey of the inner parallel instances is being overridden.

### ISSUE THREAD

**Issue by shuinan** [bpmnServer/bpmn-server#196]
![1713102819009](https://github.com/bpmnServer/bpmn-server/assets/5436066/346680f2-ae28-4b04-9be2-55b28f9fa4d8)

I have designed a workflow where parallel instances are processed within multiple subprocesses; please refer to the following BPMN file. The issue is that within the parallel multi-instance inside the subprocess, the itemKey is also the itemKey of the subprocess itself, which means I am unable to discern which instance of the parallel-instance is currently being processed.
thanks!

<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="Process_1" isExecutable="false">
    <bpmn2:startEvent id="StartEvent_1">
      <bpmn2:extensionElements>
        <camunda:executionListener event="start">
          <camunda:script scriptFormat="JavaScript">data.leaders = [1,2,3]</camunda:script>
        </camunda:executionListener>
      </bpmn2:extensionElements>
      <bpmn2:outgoing>Flow_1lzbv9d</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:sequenceFlow id="Flow_1lzbv9d" sourceRef="StartEvent_1" targetRef="Activity_0ojqzkr" />
    <bpmn2:subProcess id="Activity_0ojqzkr">
      <bpmn2:incoming>Flow_1lzbv9d</bpmn2:incoming>
      <bpmn2:outgoing>Flow_19cluov</bpmn2:outgoing>
      <bpmn2:multiInstanceLoopCharacteristics camunda:collection="data.leaders" />
      <bpmn2:startEvent id="Event_0fdexff">
        <bpmn2:outgoing>Flow_17wqt4t</bpmn2:outgoing>
      </bpmn2:startEvent>
      <bpmn2:sequenceFlow id="Flow_17wqt4t" sourceRef="Event_0fdexff" targetRef="Activity_1ovjaeh" />
      <bpmn2:sequenceFlow id="Flow_0xq3f36" sourceRef="Activity_1ovjaeh" targetRef="Activity_1eb4i8t" />
      <bpmn2:endEvent id="Event_0fptwol">
        <bpmn2:incoming>Flow_0uc9q44</bpmn2:incoming>
      </bpmn2:endEvent>
      <bpmn2:sequenceFlow id="Flow_0uc9q44" sourceRef="Activity_1eb4i8t" targetRef="Event_0fptwol" />
      <bpmn2:userTask id="Activity_1ovjaeh">
        <bpmn2:extensionElements>
          <camunda:executionListener event="start">
            <camunda:script scriptFormat="JavaScript">data.workers = [11,22]</camunda:script>
          </camunda:executionListener>
        </bpmn2:extensionElements>
        <bpmn2:incoming>Flow_17wqt4t</bpmn2:incoming>
        <bpmn2:outgoing>Flow_0xq3f36</bpmn2:outgoing>
      </bpmn2:userTask>
      <bpmn2:userTask id="Activity_1eb4i8t">
        <bpmn2:documentation>data.workers</bpmn2:documentation>
        <bpmn2:extensionElements>
          <camunda:executionListener event="start">
            <camunda:script scriptFormat="JavaScript">console.log("cur data, ", data);
console.log("cur item, ", item);</camunda:script>
          </camunda:executionListener>
        </bpmn2:extensionElements>
        <bpmn2:incoming>Flow_0xq3f36</bpmn2:incoming>
        <bpmn2:outgoing>Flow_0uc9q44</bpmn2:outgoing>
        <bpmn2:multiInstanceLoopCharacteristics camunda:collection="data.workers" />
      </bpmn2:userTask>
    </bpmn2:subProcess>
    <bpmn2:endEvent id="Event_0ocx1zv">
      <bpmn2:incoming>Flow_19cluov</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_19cluov" sourceRef="Activity_0ojqzkr" targetRef="Event_0ocx1zv" />
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNEdge id="Flow_1lzbv9d_di" bpmnElement="Flow_1lzbv9d">
        <di:waypoint x="418" y="258" />
        <di:waypoint x="570" y="258" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_19cluov_di" bpmnElement="Flow_19cluov">
        <di:waypoint x="1230" y="330" />
        <di:waypoint x="1352" y="330" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0ocx1zv_di" bpmnElement="Event_0ocx1zv">
        <dc:Bounds x="1352" y="312" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="382" y="240" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0yo7vas_di" bpmnElement="Activity_0ojqzkr" isExpanded="true">
        <dc:Bounds x="570" y="230" width="660" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_17wqt4t_di" bpmnElement="Flow_17wqt4t">
        <di:waypoint x="715" y="330" />
        <di:waypoint x="770" y="330" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0xq3f36_di" bpmnElement="Flow_0xq3f36">
        <di:waypoint x="870" y="330" />
        <di:waypoint x="930" y="330" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0uc9q44_di" bpmnElement="Flow_0uc9q44">
        <di:waypoint x="1030" y="330" />
        <di:waypoint x="1092" y="330" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0fdexff_di" bpmnElement="Event_0fdexff">
        <dc:Bounds x="678.6666666666666" y="312" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0fptwol_di" bpmnElement="Event_0fptwol">
        <dc:Bounds x="1092" y="312" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1ohrhif_di" bpmnElement="Activity_1ovjaeh">
        <dc:Bounds x="770" y="290" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0vc6s6g_di" bpmnElement="Activity_1eb4i8t">
        <dc:Bounds x="930" y="290" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>

**Comment by shuinan** [comment]
Does this approach not support nested loops, and are there alternative methods available? Desperately seeking help!

**Comment by ralphhanna** [comment]
Investigating...

**Comment by ralphhanna** [comment]
Fixed in release 2.1.13 
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/ba7d6b47-fdd4-483b-9daa-97dc57836f5d)
![image](https://github.com/bpmnServer/bpmn-server/assets/11893416/4d81c3be-0cad-41d8-acca-4d3a0205b75a)

**Comment by shuinan** [comment]
thanks！  I use “npm install" at project bpmn-web, but the bpmn-server's version is 2.1.12 still, how to get the version 2.1.13 ?

**Comment by ralphhanna** [comment]
```
npm update bpmn-server
```

**Comment by shuinan** [comment]
all are ok! thanks!
