### ISSUE TITLE
Additional variables and how to persist them

### ISSUE THREAD

**Issue by TheLethalGoose** [bpmnServer/bpmn-server#201]
For exceuting usertasks i need some additional data from the modeler. What would be a good field in the usertask for additional variables and how can i persist them in the instance? Maybe Extension Properties?

**Comment by ralphhanna** [comment]
You can use data object to store variables across items or item.vars object

**Comment by TheLethalGoose** [comment]
I mean: How can I assign a variable the data object in the Camunda Modeler?

Can I use Inputs/Outputs, or do I need to define an Execution Listener?

For example:

I have two user tasks and want a variable, defined in the modeler, to be assigned to data.variable when these tasks are reached.

**Comment by ralphhanna** [comment]
Yes, you can a listener event
