### ISSUE TITLE
Unable to edit model

### ISSUE THREAD

**Issue by jonathanfalkner** [bpmnServer/bpmn-server#204]
I followed the installation instructions, loaded up the site, everything loads fine, but when I click the model button to edit the model, the model does not render. I get the following error in the console:
![image](https://github.com/bpmnServer/bpmn-server/assets/1605838/4c7fbb3a-0f43-4747-b680-69843d70ec50)

**Comment by ralphhanna** [comment]
I am very puzzled indeed, this error has no bearing on the editor, you just ignore it, but editor should load. 
Try ignore the error

**Comment by ralphhanna** [comment]
A simple refresh would solve this problem.

Thanks
