### ISSUE TITLE
getDefinition method, instead of definitionsPath

### ISSUE THREAD

**Issue by linonetwo** [bpmnServer/bpmn-server#207]
I'm storing all BPMN files inside db, and can load them with id, instead of filename. Can definitionsPath (and other fs related fields) be optional? And allow loading everything with custom callback?

**Comment by ralphhanna** [comment]
Yes, you don't have to use definitionsPath
Not sure what you mean by custom callback, as in a method in appDelegate?

**Comment by linonetwo** [comment]
If I learned correctly, AppDelegate is the externalWorker (in camunda 8 concept). External task and JS eval happens here.

And definitionsPath is the place to read BPMN files. If I'm not using it, where will bpmn-server load the BPMN definition that is needed?

> by custom callback, as in a method in appDelegate

Yes, this can be in AppDelegate Class

**Comment by linonetwo** [comment]
I should use `dataStore(server: any): IDataStore;`
