### ISSUE TITLE
serviceName is object

### ISSUE THREAD

**Issue by linonetwo** [bpmnServer/bpmn-server#213]
in DefaultAppDelegate:

```
    async serviceCalled(serviceName, data, item: Item) {
        item.log("Service called:"+serviceName+data);

    }
```

the type of serviceName is missing, but I believe it is an object, not string, because the log here is `["Service called:[object Object][object Object]"]`, when calling

```ts
await api.engine.start('log-console.bpmn', { key: 'value' }, SystemUser);
```

And the first serviceName is `{}`, so I can't get the service name here.

Also, the second `data` is actually an `_Execution` object, not the `{ key: 'value' }`

**Comment by linonetwo** [comment]
I think my BPMN file is wrong, @ralphhanna do you know how to correctly add service task? I tried Camunda modeler Camunda 7 and Camunda 8 mode, both seem not have produce correct service task.

**Comment by ralphhanna** [comment]
Service name is just a string
See https://bpmnserver.github.io/docs/examples/serviceTask/

**Comment by linonetwo** [comment]
I see, Camunda modeler will produce (Camunda 8)

```xml
    <bpmn:serviceTask id="Activity_0w2oa5z">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="asdf" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0gt63a3</bpmn:incoming>
    </bpmn:serviceTask>
```

or (Camunda 7 , type External)

![图片](https://github.com/bpmnServer/bpmn-server/assets/3746270/b57479ed-b949-4723-b861-521d73fea2c5)


```xml
    <bpmn:serviceTask id="Activity_0ch8ngf" camunda:type="external" camunda:topic="asdf">
      <bpmn:incoming>Flow_0twfsx0</bpmn:incoming>
    </bpmn:serviceTask>
```

(type Java class)

```xml
    <bpmn:serviceTask id="Activity_0ch8ngf" camunda:class="asdf">
      <bpmn:incoming>Flow_0twfsx0</bpmn:incoming>
    </bpmn:serviceTask>
```

(type Connector)

```xml
    <bpmn:sequenceFlow id="Flow_0twfsx0" sourceRef="StartEvent_1" targetRef="Activity_0ch8ngf" />
    <bpmn:serviceTask id="Activity_0ch8ngf">
      <bpmn:extensionElements>
        <camunda:connector>
          <camunda:connectorId>afsd</camunda:connectorId>
        </camunda:connector>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0twfsx0</bpmn:incoming>
    </bpmn:serviceTask>
```

So this means we can't use Camunda Modeler.
But http://demo.bpmn.io/ also can't create service task, because it don't have a sidebar to input the task name.

![图片](https://github.com/bpmnServer/bpmn-server/assets/3746270/d1059f70-b9bf-41fb-84d4-632ad1f0caf1)

**Comment by linonetwo** [comment]
Is it possible to extend service task prefix support like https://github.com/paed01/bpmn-engine/blob/master/docs/Examples.md#extend-service-task-behaviour

**Comment by linonetwo** [comment]
Another question is, where is `service1(item,input)` 's `item,input` from?

---

This works

![图片](https://github.com/bpmnServer/bpmn-server/assets/3746270/02ac17b4-b641-45a9-ab2e-db860e6d73f0)

```xml
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:inputParameter name="str">The text</camunda:inputParameter>
        </camunda:inputOutput>
      </bpmn:extensionElements>
```

![图片](https://github.com/bpmnServer/bpmn-server/assets/3746270/e01f60d4-9951-4e4d-a38d-01a5ac881cac)


so it sometimes accept `camunda:` prefix

**Comment by linonetwo** [comment]
I find bpmn-server supports `camunda:delegateExpression` out-of-box!

Very surprising to me. So use delegateExpression on Camunda Modeler with Camunda 7 is enough.

Just like 

![图片](https://github.com/bpmnServer/bpmn-server/assets/3746270/02ac17b4-b641-45a9-ab2e-db860e6d73f0)
