### ISSUE TITLE
What is findEvents

### ISSUE THREAD

**Issue by linonetwo** [bpmnServer/bpmn-server#217]
```ts
export class TiddlyWikiModelsDatastore implements IModelsDatastore {
  async findEvents(query: { 'events.subType': 'Timer' }): Promise<any[]> {
    return [];
  }
```

What does its input "Timer" mean? Also what should be returned?

**Comment by linonetwo** [comment]
<img width="307" alt="截屏2024-07-23 00 10 41" src="https://github.com/user-attachments/assets/96cfe4dd-febc-48b1-9b9c-f5fe2f2bef12">

Difficult to tell from the code, and its comment is difficult to understand to me.

```ts
/**
    returns Model Events (like timers) for authorized to the user and based on specifid query
*/

     findEvents(query:any, user?: ISecureUser);
```

**Comment by ralphhanna** [comment]
bpmn models can have events that need to be processed by the engine without `engine.start`
So if a model has a start timer event, the engine need to monitor that and start the model.

**Comment by linonetwo** [comment]
Thanks, do you mean this?

<img width="430" alt="截屏2024-07-24 13 11 24" src="https://github.com/user-attachments/assets/e913a824-8128-40e2-91ab-3943af8f375a">


Currently if reading of BPMN file is triggered by `engine.start`, then how to know some bpmn file have timer node and trigger timer event?

```ts
await api.engine.start('log-console.bpmn', { key: 'value' }, SystemUser);
// only after this, the ModelsDatastore.getSource is called to get bpmn file
```

**Comment by ralphhanna** [comment]
Actually, there are few scenarios:

![image](https://github.com/user-attachments/assets/806ccad7-5803-44f9-9477-af70317f7d9a)


1. Timer Start Event
2. Message Start Event
3. Signal Start Event

On saving the model, data is parsed and those events are saved into the DB.

![image](https://github.com/user-attachments/assets/3d9281d5-67b9-4d36-b51c-a8f61d3f0d5f)

For Timer Start Events, on bpmn-server start ,findEvents is called for timers and then processed.

For Message and Signals, when a message is called, findEvents is called for the message/signal

**Comment by linonetwo** [comment]
> On saving the model

This is another question, I haven't seem this gets called. Do I need to call something to trigger this?

I find many method is not called when I only use `api.engine.start`

https://github.com/tiddly-gittly/workflow/blob/1e086573e1ba416bb762c0e1a7807ede44570f43/src/workflow-engine/engine/data/twModelDataStore.ts#L16-L62

**Comment by linonetwo** [comment]
> when a message is called

Am I understand correctly? When you `api.engine.start` a bpmn file, it register message/signal listener on computer memory, and when I trigger the "saving the model", it save to DB. And I can stop the bpmn file.

Later, when computer restart, and `new BPMNServer(config, config.logger)`, it get the infomation back, and auto load the related BPMN file based on `processId`.

**Comment by ralphhanna** [comment]
Not exactly Model save must happen first When message is fired it finds the corresponding responder; either a running workflow or a model start event; it doesn’t wait Sent from my iPhoneOn Jul 24, 2024, at 1:57 AM, lin onetwo ***@***.***> wrote:﻿

when a message is called

Am I understand correctly? When you api.engine.start a bpmn file, it register message/signal listener on computer memory, and when I trigger the "saving the model", it save to DB. And I can stop the bpmn file.
Later, when computer restart, and new BPMNServer(config, config.logger), it get the infomation back, and auto load the related BPMN file based on processId.

**Comment by linonetwo** [comment]
I will test this and write doc.
